var age = 25;
age = 30;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'sada', age: 22 };
console.log(age);
var mixed = [];
mixed.push(10);
mixed.push('army');
mixed.push(false);
console.log(mixed);
console.log(mixed[2]);
var ninja;
ninja = { name: 'yashi', age: 25 };
console.log(ninja);
ninja = { name: 25, age: 'yashi' };
console.log(ninja);
